### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by afolson** [termbacktime/termbacktime#1]
Update the README to include installation instructions. Or an INSTALL file. Up to you ;)

**Comment by LouisT** [comment]
Currently the best way to install from github could be:

```
go get github.com/termbacktime/termbacktime
cd $GOPATH/src/github.com/termbacktime/termbacktime
make install
```

Precompiled binaries for macOS and 64bit linux are on the releases page.

**Comment by LouisT** [comment]
Added install instructions to the README as well as an install bash script. See [install](https://github.com/termbacktime/termbacktime#install).
